import "../styles/globals.css";
import Navbar from "../../components/Navbar";
import AuthGate from "./AuthGate";

export const metadata = {
  title: "BookNGo",
  description: "Generated by BookNGo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthGate>
          <Navbar />
          <div>{children}</div>
        </AuthGate>
      </body>
    </html>
  );
}
