import "../styles/globals.css";

export const metadata = {
  title: "BookNGo",
  description: "Generated by BookNGo",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
          <div>{children}</div>
      </body>
    </html>
  );
}
